volumes:
  inventory_db:
  inventory_db_2:
  bff_db:
  metabase-data:

services:
  bff_db:
    image: postgres:18.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bff_db
      PGDATA: /data/postgres
    ports:
      - '5433:5432'
    volumes:
      - bff_db:/data/postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d bff_db']
      interval: 5s
      timeout: 5s
      retries: 5

  inventory_db:
    image: postgres:18.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db
      PGDATA: /data/postgres
    ports:
      - '5434:5432'
    volumes:
      - inventory_db:/data/postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d inventory_db']
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - inventory_db
      - bff_db
    environment:
      MB_DB_FILE: /metabase-data
    ports:
      - '5440:3000'
    volumes:
      - metabase-data:/metabase-data

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    ports:
      - '8080:8080'
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_URL: jdbc:postgresql://bff_db:5432/bff_db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DDL_AUTO: update
      ALLOWED_HOST_REGEX: '*'
      InventoryService_URL: http://inventory-service:8080
      TracingTool_URL: http://zipkin:9411
    depends_on:
      bff_db:
        condition: service_healthy
      # zipkin:
      #   condition: service_started

  inventory-service:
    build:
      context: .
      dockerfile: services/inventory/Dockerfile
    ports:
      - '8085:8080'
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_URL: jdbc:postgresql://inventory_db:5432/inventory_db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DDL_AUTO: update
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
      inventory_db:
        condition: service_healthy
      # zipkin:
      #   condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8090:4173'
    depends_on:
      - bff
    environment:
      bff_BASE_URL: 'http://bff:8080'
