volumes:
  inventory_db:
  bff_db:
  metabase-data:

services:
  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    ports:
      - '8080:8080'
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_URL: jdbc:postgresql://bff_db:5432/bff_db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DDL_AUTO: update
      ALLOWED_HOST_REGEX: '*'
      InventoryService_URL: http://inventory-service:8080
      TracingTool_URL: http://zipkin:9411
    depends_on:
      bff_db:
        condition: service_healthy
      # zipkin:
      #   condition: service_started

  inventory-service:
    build:
      context: .
      dockerfile: services/inventory/Dockerfile
    ports:
      - '8085:8080'
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_URL: jdbc:postgresql://inventory_db:5432/inventory_db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DDL_AUTO: update
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
      inventory_db:
        condition: service_healthy
      # zipkin:
      #   condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8090:4173'
    depends_on:
      - bff
    environment:
      bff_BASE_URL: 'http://bff:8080'
