server:
  port: 8090

com.management.cmdb:
  services:
    inventory:
      url: ${InventoryService_URL:http://localhost:8080}

spring:
  application:
    name: cmdb-gateway
  threads:
    virtual:
      enabled: true
  jmx:
    enabled: false
  cloud:
    gateway:
      server:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "localhost"
              allowedMethods:
                - GET
        webflux:
          routes:
            - id: inventory_service
              uri: ${com.management.cmdb.services.inventory.url}
              predicates:
              - Path=/api/inventory/**
              - Method=GET,POST,PUT,DELETE
              filters:
                - RewritePath=/api/inventory/?(?<segment>.*), /$\{segment}
                - LocalResponseCache=30m,500MB
                # - AddRequestHeadersIfNotPresent=X-Request, Gateway
#                - name: CircuitBreaker
#                  args:
#                    name: myCircuitBreaker
#                    fallbackUri: forward:/inCaseOfFailureUseThis
#                - name: CacheRequestBody
#                  args:
#                    bodyClass: java.lang.String

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

    com.management.cmdb.gateway:
      services:
        inventory: DEBUG

management.endpoints.web.exposure.include: '*'