package com.management.cmdb.services.inventory.service.impl;

import com.management.cmdb.services.inventory.dto.AuthorDto;
import com.management.cmdb.services.inventory.dto.ItemDto;
import com.management.cmdb.services.inventory.dto.NotificationDto;
import com.management.cmdb.services.inventory.dto.wrapper.PaginatedResponseDto;
import com.management.cmdb.services.inventory.entity.AttributeEntity;
import com.management.cmdb.services.inventory.entity.AttributeTypeEntity;
import com.management.cmdb.services.inventory.entity.ItemEntity;
import com.management.cmdb.services.inventory.entity.ItemTypeEntity;
import com.management.cmdb.services.inventory.exception.ItemExist;
import com.management.cmdb.services.inventory.exception.ItemNotExist;
import com.management.cmdb.services.inventory.exception.ItemNotValid;
import com.management.cmdb.services.inventory.exception.ItemTypeNotExist;
import com.management.cmdb.services.inventory.mapper.ItemMapper;
import com.management.cmdb.services.inventory.model.UserDetail;
import com.management.cmdb.services.inventory.repository.*;
import com.management.cmdb.services.inventory.service.ItemService;
import jakarta.transaction.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.util.ObjectUtils;

import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

@Transactional
@Service
public class ItemServiceImpl implements ItemService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ItemServiceImpl.class);

    private final ApplicationEventPublisher applicationEventPublisher;
    private final ItemRepository itemRepository;
    private final ItemTypeRepository itemTypeRepository;
    private final LinkTypeRepository linkTypeRepository;
    private final LinkRepository linkRepository;
    private final AttributeRepository attributeRepository;

    public ItemServiceImpl(ApplicationEventPublisher applicationEventPublisher, ItemRepository itemRepository, ItemTypeRepository itemTypeRepository, LinkTypeRepository linkTypeRepository, LinkRepository linkRepository, AttributeRepository attributeRepository) {
        this.applicationEventPublisher = applicationEventPublisher;
        this.itemRepository = itemRepository;
        this.itemTypeRepository = itemTypeRepository;
        this.linkTypeRepository = linkTypeRepository;
        this.linkRepository = linkRepository;
        this.attributeRepository = attributeRepository;
    }

    @Override
    @Transactional
    @Tool(description = "Tool targetItemId create a new item in the CMDB, all uuid (identifiers) will be generated by the tool so don't send it in the json, be careful that the item type already exist in the CMDB .")
    public ItemDto createItem(ItemDto newItemDto, UserDetail author) {
        // TODO check user details

        if (newItemDto == null || newItemDto.name() == null || newItemDto.description() == null) {
            throw new ItemNotValid();
        }
        if (this.itemRepository.existsByNameAndTypeLabel(newItemDto.name(), newItemDto.type().label())) {
            throw new ItemExist();
        }

        ItemTypeEntity itemTypeEntity = this.itemTypeRepository.findFirstByLabel(newItemDto.type().label())
                .orElseThrow(ItemTypeNotExist::new);

        ItemEntity itemEntity = ItemMapper.INSTANCE.toEntity(newItemDto);
        itemEntity.setUuid(UUID.randomUUID());
        itemEntity.setType(itemTypeEntity);

        Map<String, AttributeEntity> attributeMap = itemEntity.getAttributes()
                .stream().collect(Collectors.toMap(attr -> attr.getAttributeType().getLabel(), attr -> attr));
        itemEntity.getAttributes().clear();
        for (AttributeTypeEntity attributeTypeEntity : itemTypeEntity.getAttributes()) {
            AttributeEntity attribute = attributeMap.get(attributeTypeEntity.getLabel());
            if(attribute != null) {
                attribute.setUuid(UUID.randomUUID());
                attribute.setItem(itemEntity);
                attribute.setCreatedBy(author.uuid());
                attribute.setAttributeType(attributeTypeEntity);
                itemEntity.getAttributes().add(attribute);
            }
        }
        itemEntity = this.itemRepository.save(itemEntity);
        ItemDto resultItem = ItemMapper.INSTANCE.toDto(itemEntity);

        applicationEventPublisher.publishEvent(
                new NotificationDto(
                        new AuthorDto(author.email()),
                        NotificationDto.NotificationType.NEW_ITEM,
                        "Create new item",
                        resultItem.uuid()
                )
        );
        return resultItem;
    }

    @Override
    @Tool(description = "Tool targetItemId update an existing item in the CMDB")
    public ItemDto updateItem(ItemDto itemDto, UserDetail author) {
        if (itemDto == null || itemDto.uuid() == null) throw new ItemNotExist();
        ItemEntity existingItem = this.itemRepository.findById(itemDto.uuid())
                .orElseThrow(ItemTypeNotExist::new);
        existingItem.setName(itemDto.name());
        existingItem.setDescription(itemDto.description());

        ItemTypeEntity itemTypeEntity = this.itemTypeRepository.findFirstByLabel(itemDto.type().label())
                .orElseThrow(ItemTypeNotExist::new);
        existingItem.setType(itemTypeEntity);
        existingItem = this.itemRepository.save(existingItem);

        applicationEventPublisher.publishEvent(
                new NotificationDto(
                        new AuthorDto(author.email()),
                        NotificationDto.NotificationType.UPDATE_ITEM,
                        "Update item",
                        existingItem.getUuid()
                )
        );
        return ItemMapper.INSTANCE.toDto(existingItem);
    }

    @Override
    public void deleteItem(UUID itemId, UserDetail author) {
        ItemEntity existingItem = this.itemRepository.findById(itemId)
                .orElseThrow(ItemTypeNotExist::new);
        if (!existingItem.getOutgoingLinks().isEmpty()) {
            linkRepository.deleteAllBySourceItemUuidOrTargetItemUuid(existingItem.getUuid(), existingItem.getUuid());
            existingItem.getOutgoingLinks().clear();
        }
        if (!existingItem.getIncomingLinks().isEmpty()) {
            linkRepository.deleteAllBySourceItemUuidOrTargetItemUuid(existingItem.getUuid(), existingItem.getUuid());
            existingItem.getIncomingLinks().clear();
        }
        if (!existingItem.getAttributes().isEmpty()) {
            attributeRepository.deleteAllByItemUuid(existingItem.getUuid());
            existingItem.getAttributes().clear();
        }
        existingItem.setType(null);
        existingItem = this.itemRepository.save(existingItem);

        this.itemRepository.delete(existingItem);
        applicationEventPublisher.publishEvent(
                new NotificationDto(
                        new AuthorDto(author.email()),
                        NotificationDto.NotificationType.DELETE_ITEM,
                        "Update item",
                        existingItem.getUuid()
                )
        );
    }

    @Override
    @Tool(description = "Tool targetItemId find one specific item by its uuid")
    public ItemDto findItemById(UUID uuid, UserDetail userDetail) {
        return this.itemRepository.findById(uuid)
                .map(ItemMapper.INSTANCE::toDto)
                .orElseThrow(ItemNotExist::new);
    }

    @Override
    @Tool(description = "Tool targetItemId retrieve all item wich contained this item label, if you want all items put '' and the result is paginated so the page number start at 0")
    public PaginatedResponseDto<ItemDto> searchItemByNameOrType(String itemName, String itemTypeLabel, int page, int pageSize, UserDetail userDetail) {
        // TODO check user details
        if (ObjectUtils.isEmpty(itemName)) itemName = "";
        if (ObjectUtils.isEmpty(itemTypeLabel)) itemTypeLabel = "";
        Page<ItemEntity> result = this.itemRepository.searchAllByNameContainingIgnoreCaseAndTypeLabelContainingIgnoreCase(
                itemName,
                itemTypeLabel,
                PageRequest.of(page, pageSize).withSort(Sort.by("name").ascending()));
        return PaginatedResponseDto.<ItemDto, ItemEntity>toPaginatedDto(result, ItemMapper.INSTANCE::toDto);
    }

    @Override
    public PaginatedResponseDto<ItemDto> searchItemByAttribute(String itemTypeLabel, String attributeName, String attributeValue, UserDetail userDetail) {
        // TODO check user details
        if (ObjectUtils.isEmpty(itemTypeLabel)) itemTypeLabel = "%";
        List<ItemEntity> foundItem = this.itemRepository.searchAllByTypeLabelLike(itemTypeLabel).stream()
                .filter(item ->
                        item.getAttributes().stream().anyMatch(attribute ->
                            attribute.getAttributeType().getLabel().equalsIgnoreCase(attributeName)
                                    && attribute.getValueStr().equalsIgnoreCase(attributeValue)))
                .toList();
        return PaginatedResponseDto.<ItemDto, ItemEntity>toPaginatedDto(foundItem, ItemMapper.INSTANCE::toDto);
    }
}
