package com.management.cmdb.services.inventory.service.impl;

import com.management.cmdb.services.inventory.dto.AuthorDto;
import com.management.cmdb.services.inventory.dto.ItemDto;
import com.management.cmdb.services.inventory.dto.LinkDto;
import com.management.cmdb.services.inventory.dto.NotificationDto;
import com.management.cmdb.services.inventory.dto.wrapper.PaginatedResponseDto;
import com.management.cmdb.services.inventory.entity.*;
import com.management.cmdb.services.inventory.exception.*;
import com.management.cmdb.services.inventory.job.StartupJob;
import com.management.cmdb.services.inventory.mapper.ItemMapper;
import com.management.cmdb.services.inventory.model.UserDetail;
import com.management.cmdb.services.inventory.repository.ItemRepository;
import com.management.cmdb.services.inventory.repository.ItemTypeRepository;
import com.management.cmdb.services.inventory.repository.LinkTypeRepository;
import com.management.cmdb.services.inventory.service.ItemService;
import jakarta.transaction.Transactional;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.util.ObjectUtils;

import java.util.List;
import java.util.UUID;

@Service
public class ItemServiceImpl implements ItemService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ItemServiceImpl.class);

    private final ApplicationEventPublisher applicationEventPublisher;
    private final ItemRepository itemRepository;
    private final ItemTypeRepository itemTypeRepository;
    private final LinkTypeRepository linkTypeRepository;

    public ItemServiceImpl(ApplicationEventPublisher applicationEventPublisher, ItemRepository itemRepository, ItemTypeRepository itemTypeRepository, LinkTypeRepository linkTypeRepository) {
        this.applicationEventPublisher = applicationEventPublisher;
        this.itemRepository = itemRepository;
        this.itemTypeRepository = itemTypeRepository;
        this.linkTypeRepository = linkTypeRepository;
    }

    @Override
    @Transactional
    @Tool(description = "Tool targetItemId create a new item in the CMDB, all uuid (identifiers) will be generated by the tool so don't send it in the json, be careful that the item type already exist in the CMDB .")
    public ItemDto createItem(ItemDto newItemDto, UserDetail author) {
        // TODO check user details

        if (newItemDto == null || newItemDto.name() == null || newItemDto.description() == null) {
            throw new ItemNotValid();
        }
        if (this.itemRepository.existsByNameAndTypeLabel(newItemDto.name(), newItemDto.type().label())) {
            throw new ItemExist();
        }

        ItemTypeEntity itemTypeEntity = this.itemTypeRepository.findFirstByLabel(newItemDto.type().label())
                .orElseThrow(ItemTypeNotExist::new);

        ItemEntity itemEntity = ItemMapper.INSTANCE.toEntity(newItemDto);
        itemEntity.setUuid(UUID.randomUUID());
        itemEntity.setType(itemTypeEntity);

        for (AttributeEntity attribute : itemEntity.getAttributes()) {
            attribute.setUuid(UUID.randomUUID());
            attribute.setItem(itemEntity);
            attribute.setCreatedBy(author.uuid());

            AttributeTypeEntity attributeType = itemTypeEntity.getAttributes().stream()
                    .filter(attributeTypeRef -> attributeTypeRef.getLabel().equals(attribute.getAttributeType().getLabel()))
                    .findFirst().orElseThrow(ItemNotValid::new);
            attribute.setAttributeType(attributeType);
        }

        if (!itemEntity.getOutgoingLinks().isEmpty()) {
            for (LinkEntity linkEntity : itemEntity.getOutgoingLinks()) {
                linkEntity.setUuid(UUID.randomUUID());
                linkEntity.setLinkType(linkTypeRepository.findFirstByLabelIgnoreCase(newItemDto.type().label())
                        .orElseGet(() -> createLinkType(linkEntity.getLinkType(), author)));
                linkEntity.setSourceItem(itemEntity);
                ItemEntity targetItem = itemRepository.findById(linkEntity.getTargetItem().getUuid())
                        .orElseThrow(() -> new LinkedItemDoesNotExist(linkEntity.getTargetItem()));
                linkEntity.setTargetItem(targetItem);
            }
        }
        if (!itemEntity.getIncomingLinks().isEmpty()) {
            for (LinkEntity linkEntity : itemEntity.getIncomingLinks()) {
                linkEntity.setUuid(UUID.randomUUID());
                linkEntity.setLinkType(linkTypeRepository.findFirstByLabelIgnoreCase(newItemDto.type().label())
                        .orElseGet(() -> createLinkType(linkEntity.getLinkType(), author)));

                ItemEntity sourceItem = itemRepository.findById(linkEntity.getSourceItem().getUuid())
                        .orElseThrow(() -> new LinkedItemDoesNotExist(linkEntity.getSourceItem()));
                linkEntity.setSourceItem(sourceItem);
                linkEntity.setTargetItem(itemEntity);
            }
        }

        itemEntity = this.itemRepository.save(itemEntity);
        ItemDto resultItem = ItemMapper.INSTANCE.toDto(itemEntity);

        applicationEventPublisher.publishEvent(
                new NotificationDto(
                        new AuthorDto(author.email()),
                        NotificationDto.NotificationType.NEW_ITEM,
                        "Create new item",
                        resultItem.uuid()
                )
        );
        return resultItem;
    }

    private LinkTypeEntity createLinkType(LinkTypeEntity linkTypeEntity, UserDetail author) {
        if (StringUtils.isBlank(linkTypeEntity.getLabel())) throw new LinkTypeNotValid();
        linkTypeEntity.setUuid(UUID.randomUUID());
        LinkTypeEntity newLink = linkTypeRepository.save(linkTypeEntity);

        applicationEventPublisher.publishEvent(
                new NotificationDto(
                        new AuthorDto(author.email()),
                        NotificationDto.NotificationType.NEW_ITEM,
                        "Connect items",
                        newLink.getUuid()
                )
        );
        return newLink;
    }

    @Override
    @Tool(description = "Tool targetItemId update an existing item in the CMDB")
    public ItemDto updateItem(ItemDto itemDto, UserDetail author) {
        ItemEntity existingItem = this.itemRepository.findById(itemDto.uuid())
                .orElseThrow(ItemTypeNotExist::new);
        existingItem.setName(itemDto.name());
        existingItem.setDescription(itemDto.description());

        if (!itemDto.outgoingLinks().isEmpty()) {
            // TODO Delete unupdated links ?
            for (LinkDto linkDto : itemDto.outgoingLinks()) {
                LinkEntity linkEntity = new LinkEntity();
                linkEntity.setUuid(UUID.randomUUID());
                linkEntity.setLinkType(linkTypeRepository.findFirstByLabelIgnoreCase(linkDto.linkType().label())
                        .orElse(StartupJob.communicate_with));
                linkEntity.setSourceItem(existingItem);
                ItemEntity targetItem = itemRepository.findById(linkDto.targetItemId())
                        .orElseThrow(() -> new LinkedItemDoesNotExist(linkDto.targetItemId()));
                linkEntity.setTargetItem(targetItem);
                existingItem.getOutgoingLinks().add(linkEntity);
            }
        }
        if (!itemDto.incomingLinks().isEmpty()) {
            // TODO Delete unupdated links ?
            for (LinkDto linkDto : itemDto.incomingLinks()) {
                LinkEntity linkEntity = new LinkEntity();
                linkEntity.setUuid(UUID.randomUUID());
                linkEntity.setLinkType(linkTypeRepository.findFirstByLabelIgnoreCase(linkDto.linkType().label())
                        .orElse(StartupJob.communicate_with));

                ItemEntity sourceItem = itemRepository.findById(linkDto.sourceItemId())
                        .orElseThrow(() -> new LinkedItemDoesNotExist(linkDto.sourceItemId()));
                linkEntity.setSourceItem(sourceItem);
                linkEntity.setTargetItem(existingItem);
                existingItem.getIncomingLinks().add(linkEntity);
            }
        }
        existingItem = this.itemRepository.save(existingItem);

        applicationEventPublisher.publishEvent(
                new NotificationDto(
                        new AuthorDto(author.email()),
                        NotificationDto.NotificationType.UPDATE_ITEM,
                        "Update item",
                        existingItem.getUuid()
                )
        );
        return ItemMapper.INSTANCE.toDto(existingItem);
    }

    @Override
    public void deleteItem(UUID itemId, UserDetail author) {
        ItemEntity existingItem = this.itemRepository.findById(itemId)
                .orElseThrow(ItemTypeNotExist::new);
        this.itemRepository.delete(existingItem);
        applicationEventPublisher.publishEvent(
                new NotificationDto(
                        new AuthorDto(author.email()),
                        NotificationDto.NotificationType.DELETE_ITEM,
                        "Update item",
                        existingItem.getUuid()
                )
        );
    }

    @Override
    @Tool(description = "Tool targetItemId find one specific item by its uuid")
    public ItemDto findItemById(UUID uuid, UserDetail userDetail) {
        return this.itemRepository.findById(uuid)
                .map(ItemMapper.INSTANCE::toDto)
                .orElseThrow(ItemTypeNotExist::new);
    }

    @Override
    @Tool(description = "Tool targetItemId retrieve all item wich contained this item label, if you want all items put '' and the result is paginated so the page number start at 0")
    public PaginatedResponseDto<ItemDto> searchItemByNameOrType(String itemName, String itemTypeLabel, int page, int pageSize, UserDetail userDetail) {
        // TODO check user details
        if (ObjectUtils.isEmpty(itemName)) itemName = "";
        Page<ItemEntity> result = this.itemRepository.searchAllByNameContainingIgnoreCaseOrTypeLabel(
                itemName,
                itemTypeLabel,
                PageRequest.of(page, pageSize));
        return PaginatedResponseDto.<ItemDto, ItemEntity>toPaginatedDto(result, ItemMapper.INSTANCE::toDto);
    }

    @Override
    public PaginatedResponseDto<ItemDto> searchItemByAttribute(String itemTypeLabel, String attributeName, String attributeValue, UserDetail userDetail) {
        // TODO check user details
        if (ObjectUtils.isEmpty(itemTypeLabel)) itemTypeLabel = "%";
        List<ItemEntity> foundItem = this.itemRepository.searchAllByTypeLabelLike(itemTypeLabel).stream()
                .filter(item ->
                        item.getAttributes().stream().anyMatch(attribute ->
                            attribute.getAttributeType().getLabel().equalsIgnoreCase(attributeName)
                                    && attribute.getValueStr().equalsIgnoreCase(attributeValue)))
                .toList();
        return PaginatedResponseDto.<ItemDto, ItemEntity>toPaginatedDto(foundItem, ItemMapper.INSTANCE::toDto);
    }
}
