server.port=${PORT:8096}

repository-scrapper.server.local_storage_path=<path_to_temp_folder>

repository-scrapper.github.token=<github_pat_****>
repository-scrapper.github.organization=<organization_name>
repository-scrapper.github.repository_match_regex=<repo_name_regex>

logging.level.com.management.cmdb.services.aggregator.github_analyzer=debug
