package com.management.cmdb.services.aggregator.syslog.server;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

/**
 * Source: https://docs.paloaltonetworks.com/ngfw/administration/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/traffic-log-fields#idbe18d2d4-9eb8-4966-bec8-df3a6de70e66
 */
public record PaloAltoTrafficLog (
    Instant receiveTime,
    String serial,
    String type,
    String subtype,
    Instant timeGenerated,
    String src,
    String dst,
    String natsrc,
    String natdst,
    String rule,
    String srcuser,
    String dstuser,
    String app,
    String vsys,
    String from,
    String to,
    String inboundIf,
    String outboundIf,
    String logset,
    String sessionId,
    int repeatCnt,
    int sport,
    int dport,
    int natsport,
    int natdport,
    String flags,
    String proto,
    String action,
    long bytes,
    long bytesSent,
    long bytesReceived,
    long packets,
    Instant start,
    long elapsed,
    String category,
    String seqno,
    String actionflags,
    String srcloc,
    String dstloc,
    long pktsSent,
    long pktsReceived,
    String sessionEndReason,
    String dgHierLevel1,
    String dgHierLevel2,
    String dgHierLevel3,
    String dgHierLevel4,
    String vsysName,
    String deviceName,
    String actionSource,
    String srcUuid,
    String dstUuid,
    String tunnelidImsi,
    String monitortagImei,
    String parentSessionId,
    Instant parentStartTime,
    String tunnel,
    String assocId,
    String chunks,
    String chunksSent,
    String chunksReceived,
    String ruleUuid,
    String http2Connection,
    int linkChangeCount,
    String policyId,
    String linkSwitches,
    String sdwanCluster,
    String sdwanDeviceType,
    String sdwanClusterType,
    String sdwanSite,
    String dynusergroupName,
    String xffIp,
    String srcCategory,
    String srcProfile,
    String srcModel,
    String srcVendor,
    String srcOsfamily,
    String srcOsversion,
    String srcHost,
    String srcMac,
    String dstCategory,
    String dstProfile,
    String dstModel,
    String dstVendor,
    String dstOsfamily,
    String dstOsversion,
    String dstHost,
    String dstMac,
    String containerId,
    String podNamespace,
    String podName,
    String srcEdl,
    String dstEdl,
    String hostid,
    String serialnumber,
    String srcDag,
    String dstDag,
    String sessionOwner,
    Instant highResTimestamp,
    String nssaiSst,
    String nssaiSd,
    String subcategoryOfApp,
    String categoryOfApp,
    String technologyOfApp,
    int riskOfApp,
    String characteristicOfApp,
    String containerOfApp,
    String tunneledApp,
    boolean isSaasOfApp,
    boolean sanctionedStateOfApp,
    boolean offloaded,
    String flowType,
    String clusterName
) {

    public static PaloAltoTrafficLog parse(String rawMessage) {
        Map<String, String> fields = new HashMap<>();
        String[] parts = rawMessage.split(", ");
        for (String part : parts) {
            String[] keyValue = part.split("=", 2);
            if (keyValue.length == 2) {
                fields.put(keyValue[0].trim(), keyValue[1].trim());
            }
        }

        return new PaloAltoTrafficLog(
                fields.containsKey("receive_time") ? Instant.parse(fields.get("receive_time")) : null,
                fields.get("serial"),
                fields.get("type"),
                fields.get("subtype"),
                fields.containsKey("time_generated") ? Instant.parse(fields.get("time_generated")) : null,
                fields.get("src"),
                fields.get("dst"),
                fields.get("natsrc"),
                fields.get("natdst"),
                fields.get("rule"),
                fields.get("srcuser"),
                fields.get("dstuser"),
                fields.get("app"),
                fields.get("vsys"),
                fields.get("from"),
                fields.get("to"),
                fields.get("inbound_if"),
                fields.get("outbound_if"),
                fields.get("logset"),
                fields.get("sessionid"),
                fields.containsKey("repeatcnt") ? Integer.parseInt(fields.get("repeatcnt")) : 0,
                fields.containsKey("sport") ? Integer.parseInt(fields.get("sport")) : 0,
                fields.containsKey("dport") ? Integer.parseInt(fields.get("dport")) : 0,
                fields.containsKey("natsport") ? Integer.parseInt(fields.get("natsport")) : 0,
                fields.containsKey("natdport") ? Integer.parseInt(fields.get("natdport")) : 0,
                fields.get("flags"),
                fields.get("proto"),
                fields.get("action"),
                fields.containsKey("bytes") ? Long.parseLong(fields.get("bytes")) : 0L,
                fields.containsKey("bytes_sent") ? Long.parseLong(fields.get("bytes_sent")) : 0L,
                fields.containsKey("bytes_received") ? Long.parseLong(fields.get("bytes_received")) : 0L,
                fields.containsKey("packets") ? Long.parseLong(fields.get("packets")) : 0L,
                fields.containsKey("start") ? Instant.parse(fields.get("start")) : null,
                fields.containsKey("elapsed") ? Long.parseLong(fields.get("elapsed")) : 0L,
                fields.get("category"),
                fields.get("seqno"),
                fields.get("actionflags"),
                fields.get("srcloc"),
                fields.get("dstloc"),
                fields.containsKey("pkts_sent") ? Long.parseLong(fields.get("pkts_sent")) : 0L,
                fields.containsKey("pkts_received") ? Long.parseLong(fields.get("pkts_received")) : 0L,
                fields.get("session_end_reason"),
                fields.get("dg_hier_level_1"),
                fields.get("dg_hier_level_2"),
                fields.get("dg_hier_level_3"),
                fields.get("dg_hier_level_4"),
                fields.get("vsys_name"),
                fields.get("device_name"),
                fields.get("action_source"),
                fields.get("src_uuid"),
                fields.get("dst_uuid"),
                fields.get("tunnelid"),
                fields.get("monitortag"),
                fields.get("parent_session_id"),
                fields.containsKey("parent_start_time") ? Instant.parse(fields.get("parent_start_time")) : null,
                fields.get("tunnel"),
                fields.get("assoc_id"),
                fields.get("chunks"),
                fields.get("chunks_sent"),
                fields.get("chunks_received"),
                fields.get("rule_uuid"),
                fields.get("http2_connection"),
                fields.containsKey("link_change_count") ? Integer.parseInt(fields.get("link_change_count")) : 0,
                fields.get("policy_id"),
                fields.get("link_switches"),
                fields.get("sdwan_cluster"),
                fields.get("sdwan_device_type"),
                fields.get("sdwan_cluster_type"),
                fields.get("sdwan_site"),
                fields.get("dynusergroup_name"),
                fields.get("xff_ip"),
                fields.get("src_category"),
                fields.get("src_profile"),
                fields.get("src_model"),
                fields.get("src_vendor"),
                fields.get("src_osfamily"),
                fields.get("src_osversion"),
                fields.get("src_host"),
                fields.get("src_mac"),
                fields.get("dst_category"),
                fields.get("dst_profile"),
                fields.get("dst_model"),
                fields.get("dst_vendor"),
                fields.get("dst_osfamily"),
                fields.get("dst_osversion"),
                fields.get("dst_host"),
                fields.get("dst_mac"),
                fields.get("container_id"),
                fields.get("pod_namespace"),
                fields.get("pod_name"),
                fields.get("src_edl"),
                fields.get("dst_edl"),
                fields.get("hostid"),
                fields.get("serialnumber"),
                fields.get("src_dag"),
                fields.get("dst_dag"),
                fields.get("session_owner"),
                fields.containsKey("high_res_timestamp") ? Instant.parse(fields.get("high_res_timestamp")) : null,
                fields.get("nssai_sst"),
                fields.get("nssai_sd"),
                fields.get("subcategory_of_app"),
                fields.get("category_of_app"),
                fields.get("technology_of_app"),
                fields.containsKey("risk_of_app") ? Integer.parseInt(fields.get("risk_of_app")) : 0,
                fields.get("characteristic_of_app"),
                fields.get("container_of_app"),
                fields.get("tunneled_app"),
                fields.containsKey("is_saas_of_app") && "1".equals(fields.get("is_saas_of_app")),
                fields.containsKey("sanctioned_state_of_app") && "1".equals(fields.get("sanctioned_state_of_app")),
                fields.containsKey("offloaded") && "1".equals(fields.get("offloaded")),
                fields.get("flow_type"),
                fields.get("cluster_name")
        );
    }
}
