# Server properties
## Database properties ##


# Logger properties
logging.level.root=INFO
logging.level.com.management.cmdb.services.inventory=DEBUG
logging.level.org.springframework.data.jpa=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework.modulith=DEBUG
